# Generate mise's session-dependent code before config.nu imports it.
# Zoxide's static integration is generated by bootstrap.nu, not on every launch.
mkdir $nu.cache-dir
^mise activate nu | save --force ($nu.cache-dir | path join "mise.nu")
