KeyBind:
  down:
    - Enter
    - Down
    - ctrl+n
    - j
  up:
    - Up
    - ctrl+p
    - k
  top:
    - Home
    - g
  bottom:
    - End
    - G
  goto: []
  line_number_mode: []
  jump_target: []
