[tools]
node = "latest"
python = "latest"
go = "latest"
rust = "latest"
"npm:pnpm" = "latest"
"github:ajeetdsouza/zoxide" = { version = "latest", asset_pattern = "zoxide-*-aarch64-linux-android.tar.gz" }
"github:starship/starship" = { version = "latest", asset_pattern = "starship-aarch64-unknown-linux-musl.tar.gz" }
"github:sharkdp/fd" = { version = "latest", asset_pattern = "fd-*-aarch64-unknown-linux-musl.tar.gz" }
"github:jj-vcs/jj" = { version = "latest", asset_pattern = "jj-*-aarch64-unknown-linux-musl.tar.gz" }
eza = "latest"
tmux = "latest"

[settings]
os = "linux"
libc = "glibc"
experimental = true

[settings.python]
uv_venv_auto = "source"
